# html lang
language: en

theme:
  color: '#2d2d2d'
  avatar: '/images/avatar.jpg'
# main menu navigation
menu:
  home: /
  articles: /archives
  about: /about

# Customize the overview with the most recent blog posts on the index page.
# Options:
#   - show_all_posts: whether to show all available posts.
#   - post_count: whether to show only the x most recent posts.
#   - sort_updated: sort posts by last modification date instead of creation date.
posts_overview:
  show_all_posts: false
  post_count: 5
  sort_updated: false

# Customize the archive view.
# Options:
#   - sort_updated: sort posts by last modification date instead of creation date.
# Note: this does not work together with pagination, since the pagination
# plugin will sort pages by date of creation.
archive:
  sort_updated: false

post:
  show_updated: false

social:
  enable: false
  links:
   GitHub:
     icon: github
     link: https://github.com/yourname
   Email:
     icon: envelope
     link: mailto:your@email.address
   Weibo:
     icon: weibo
     link: https://weibo.com/yourname
   Twitter:
     icon: twitter
     link: https://twitter.com/yourname
   Instagram:
     icon: instagram
     link: https://instagram.com/yourname